# Generated by Django 3.2.18 on 2023-04-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0002_rename_choise_text_choise_choice_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
    ]
